#!/usr/bin/env bash

# Backup all the current work
git add .

# Commit all the latest changes
if [ -z "$1" ]; then
  read -r -p "Please enter the commit message: " -r
  [ -z "$REPLY" ] && return
  git commit -m "$REPLY"
else
  git commit -m "$@"
fi

git push -f bb dev
