#!/usr/bin/env bash

# If the site exists
if [ -d _site ]; then
  mv _site/resume tmp/resume
fi

# If the site does not exist
if [ ! -d _site ]; then

  # Initialize git to target GitHub
  echo "=> Initializing GitHub clone"
  mkdir _site
  cd _site
  git init
  git remote add gh git@github.com:ElMassimo/elmassimo.github.io.git
  git fetch gh master
  git checkout master
  cd ..
fi

mv tmp/resume _site/resume

# Rebuild site
echo "=> Building Jekyll Site"
bin/jekyll build --lsi --trace "$@"
