#!/usr/bin/env bash

# Remove compiled site.
find _site -mindepth 1 -maxdepth 1 -type d | grep -v .git | grep -v resume | xargs rm -r

# Remove images.
rm -R -f tmp

# Remove sass cache.
rm -R -f .sass-cache
