#!/usr/bin/env bash

# Commit all the latest changes
if [ -z "$1" ]; then
  read -r -p "Please enter the commit message: " -r
  [ -z "$REPLY" ] && exit
  message="$REPLY"
else
  message="$@"
fi

exe/save "$message"
exe/gh "$message"
