#!/usr/bin/env ruby
# frozen_string_literal: true

# Build the site.
`exe/build`

# Check all the links in the site.
require 'html-proofer'

valid = HTMLProofer.check_directory('./_site', url_ignore: ['#']).run
`exit 1` unless valid
