#!/bin/sh
set -e
cd "$(dirname "$0")/.."

echo "\n== Building the site =="
exe/build

echo "\n== Proofing HTML links =="
bin/htmlproofer --assume-extension --allow-hash-href ./_site --typhoeus-config '{ "ssl_verifypeer": false, "headers": { "User-Agent": "Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1" } }' --http-status-ignore 999
