#!/bin/sh

# exe/serve: Starts the Jekyll development server.
set -e
cd "$(dirname "$0")/.."
exe/rename_window "server"

# Ensure everything in the app is up to date.
exe/update

# Ensure the environment is set as development
test -z "$RACK_ENV" && RACK_ENV='development'
export RACK_ENV

# Boot the app and any other necessary processes.
echo "\n== Starting server =="

bin/jekyll serve --drafts "$@"
