#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'

# path to your application root.
APP_ROOT = File.expand_path('..', __dir__)

def system!(*args)
  system(*args) || abort("\n== Command #{ args } failed ==")
end

# exe/update: Resolves all the dependencies that the app requires to run.
FileUtils.cd APP_ROOT do
  puts '== Installing gem dependencies =='
  system! 'gem install bundler --conservative'
  system('bundle check') || system!('bundle install --quiet')
end
